//Code automatically generated by SOLSTICE
pragma solidity ^0.4.19;
contract liquid_demo {
  //Permissions and empowerments.
  //Exogenous events.
  bool add_member_perm_wildcard_on_0 = false;
  bool add_member_pow_wildcard_on_0 = false;
  mapping (address => bool) private add_member_perm_map_on_0;
  mapping (address => bool) private add_member_pow_map_on_0;
  bool add_member_perm_wildcard_on_1 = false;
  bool add_member_pow_wildcard_on_1 = false;
  mapping (address => bool) private add_member_perm_map_on_1;
  mapping (address => bool) private add_member_pow_map_on_1;
  bool approved_perm_wildcard_on_0 = false;
  bool approved_pow_wildcard_on_0 = false;
  mapping (string => bool) private approved_perm_map_on_0;
  mapping (string => bool) private approved_pow_map_on_0;
  bool create_contract_perm_wildcard_on_0 = true;
  bool create_contract_pow_wildcard_on_0 = true;
  mapping (address => bool) private create_contract_perm_map_on_0;
  mapping (address => bool) private create_contract_pow_map_on_0;
  bool deadline_perm_wildcard_on_0 = false;
  bool deadline_pow_wildcard_on_0 = false;
  mapping (string => bool) private deadline_perm_map_on_0;
  mapping (string => bool) private deadline_pow_map_on_0;
  bool new_proposal_perm_wildcard_on_0 = false;
  bool new_proposal_pow_wildcard_on_0 = false;
  mapping (string => bool) private new_proposal_perm_map_on_0;
  mapping (string => bool) private new_proposal_pow_map_on_0;
  bool new_proposal_perm_wildcard_on_1 = false;
  bool new_proposal_pow_wildcard_on_1 = false;
  mapping (address => bool) private new_proposal_perm_map_on_1;
  mapping (address => bool) private new_proposal_pow_map_on_1;
  bool new_proposal_perm_wildcard_on_2 = false;
  bool new_proposal_pow_wildcard_on_2 = false;
  mapping (address => bool) private new_proposal_perm_map_on_2;
  mapping (address => bool) private new_proposal_pow_map_on_2;
  bool new_proposal_perm_wildcard_on_3 = false;
  bool new_proposal_pow_wildcard_on_3 = false;
  mapping (string => bool) private new_proposal_perm_map_on_3;
  mapping (string => bool) private new_proposal_pow_map_on_3;
  bool new_proposal_perm_wildcard_on_4 = false;
  bool new_proposal_pow_wildcard_on_4 = false;
  mapping (string => bool) private new_proposal_perm_map_on_4;
  mapping (string => bool) private new_proposal_pow_map_on_4;
  bool nosupport_perm_wildcard_on_0 = false;
  bool nosupport_pow_wildcard_on_0 = false;
  mapping (address => bool) private nosupport_perm_map_on_0;
  mapping (address => bool) private nosupport_pow_map_on_0;
  bool nosupport_perm_wildcard_on_1 = false;
  bool nosupport_pow_wildcard_on_1 = false;
  mapping (string => bool) private nosupport_perm_map_on_1;
  mapping (string => bool) private nosupport_pow_map_on_1;
  bool nosupport_perm_wildcard_on_2 = false;
  bool nosupport_pow_wildcard_on_2 = false;
  mapping (string => bool) private nosupport_perm_map_on_2;
  mapping (string => bool) private nosupport_pow_map_on_2;
  bool support_perm_wildcard_on_0 = false;
  bool support_pow_wildcard_on_0 = false;
  mapping (address => bool) private support_perm_map_on_0;
  mapping (address => bool) private support_pow_map_on_0;
  bool support_perm_wildcard_on_1 = false;
  bool support_pow_wildcard_on_1 = false;
  mapping (string => bool) private support_perm_map_on_1;
  mapping (string => bool) private support_pow_map_on_1;
  bool support_perm_wildcard_on_2 = false;
  bool support_pow_wildcard_on_2 = false;
  mapping (string => bool) private support_perm_map_on_2;
  mapping (string => bool) private support_pow_map_on_2;
  
  //Inst events.
  bool inst_add_member_perm_wildcard_on_0 = false;
  bool inst_add_member_pow_wildcard_on_0 = false;
  mapping (address => bool) private inst_add_member_perm_map_on_0;
  mapping (address => bool) private inst_add_member_pow_map_on_0;
  bool inst_add_member_perm_wildcard_on_1 = false;
  bool inst_add_member_pow_wildcard_on_1 = false;
  mapping (address => bool) private inst_add_member_perm_map_on_1;
  mapping (address => bool) private inst_add_member_pow_map_on_1;
  bool inst_approved_perm_wildcard_on_0 = false;
  bool inst_approved_pow_wildcard_on_0 = false;
  mapping (string => bool) private inst_approved_perm_map_on_0;
  mapping (string => bool) private inst_approved_pow_map_on_0;
  bool inst_create_contract_perm_wildcard_on_0 = true;
  bool inst_create_contract_pow_wildcard_on_0 = false;
  mapping (address => bool) private inst_create_contract_perm_map_on_0;
  mapping (address => bool) private inst_create_contract_pow_map_on_0;
  bool inst_deadline_perm_wildcard_on_0 = false;
  bool inst_deadline_pow_wildcard_on_0 = false;
  mapping (string => bool) private inst_deadline_perm_map_on_0;
  mapping (string => bool) private inst_deadline_pow_map_on_0;
  bool inst_new_proposal_perm_wildcard_on_0 = false;
  bool inst_new_proposal_pow_wildcard_on_0 = false;
  mapping (string => bool) private inst_new_proposal_perm_map_on_0;
  mapping (string => bool) private inst_new_proposal_pow_map_on_0;
  bool inst_new_proposal_perm_wildcard_on_1 = false;
  bool inst_new_proposal_pow_wildcard_on_1 = false;
  mapping (address => bool) private inst_new_proposal_perm_map_on_1;
  mapping (address => bool) private inst_new_proposal_pow_map_on_1;
  bool inst_new_proposal_perm_wildcard_on_2 = false;
  bool inst_new_proposal_pow_wildcard_on_2 = false;
  mapping (address => bool) private inst_new_proposal_perm_map_on_2;
  mapping (address => bool) private inst_new_proposal_pow_map_on_2;
  bool inst_new_proposal_perm_wildcard_on_3 = false;
  bool inst_new_proposal_pow_wildcard_on_3 = false;
  mapping (string => bool) private inst_new_proposal_perm_map_on_3;
  mapping (string => bool) private inst_new_proposal_pow_map_on_3;
  bool inst_new_proposal_perm_wildcard_on_4 = false;
  bool inst_new_proposal_pow_wildcard_on_4 = false;
  mapping (string => bool) private inst_new_proposal_perm_map_on_4;
  mapping (string => bool) private inst_new_proposal_pow_map_on_4;
  bool inst_nosupport_perm_wildcard_on_0 = false;
  bool inst_nosupport_pow_wildcard_on_0 = false;
  mapping (address => bool) private inst_nosupport_perm_map_on_0;
  mapping (address => bool) private inst_nosupport_pow_map_on_0;
  bool inst_nosupport_perm_wildcard_on_1 = false;
  bool inst_nosupport_pow_wildcard_on_1 = false;
  mapping (string => bool) private inst_nosupport_perm_map_on_1;
  mapping (string => bool) private inst_nosupport_pow_map_on_1;
  bool inst_nosupport_perm_wildcard_on_2 = false;
  bool inst_nosupport_pow_wildcard_on_2 = false;
  mapping (string => bool) private inst_nosupport_perm_map_on_2;
  mapping (string => bool) private inst_nosupport_pow_map_on_2;
  bool inst_support_perm_wildcard_on_0 = false;
  bool inst_support_pow_wildcard_on_0 = false;
  mapping (address => bool) private inst_support_perm_map_on_0;
  mapping (address => bool) private inst_support_pow_map_on_0;
  bool inst_support_perm_wildcard_on_1 = false;
  bool inst_support_pow_wildcard_on_1 = false;
  mapping (string => bool) private inst_support_perm_map_on_1;
  mapping (string => bool) private inst_support_pow_map_on_1;
  bool inst_support_perm_wildcard_on_2 = false;
  bool inst_support_pow_wildcard_on_2 = false;
  mapping (string => bool) private inst_support_perm_map_on_2;
  mapping (string => bool) private inst_support_pow_map_on_2;
  
  //Fluents
  mapping(address => bool) public against_0;
  mapping(string => bool) public against_1;
  mapping(address => bool) public is_member_0;
  mapping(string => bool) public proposal_active_0;
  mapping(string => bool) public proposal_amount_0;
  mapping(string => bool) public proposal_amount_1;
  mapping(string => bool) public proposal_approved_0;
  mapping(string => bool) public proposal_beneficiary_0;
  mapping(address => bool) public proposal_beneficiary_1;
  mapping(string => bool) public proposal_justification_0;
  mapping(string => bool) public proposal_justification_1;
  mapping(string => bool) public proposal_owner_0;
  mapping(address => bool) public proposal_owner_1;
  mapping(address => bool) public supports_0;
  mapping(string => bool) public supports_1;
  
  //Violation events
  event not_member(address a);
  
  function liquid_demo() public {
    //Function calls for initial 'create_contract' event.
    inst_create_contract(msg.sender);
  }
  function inst_add_member(address a, address b) private {
    require((inst_add_member_perm_wildcard_on_0 || inst_add_member_perm_map_on_0[a]) && (inst_add_member_perm_wildcard_on_1 || inst_add_member_perm_map_on_1[b]));
    new_proposal_perm_wildcard_on_0 = true;
    new_proposal_perm_wildcard_on_1 = true;
    new_proposal_perm_wildcard_on_2 = true;
    new_proposal_perm_wildcard_on_3 = true;
    new_proposal_perm_wildcard_on_4 = true;
    new_proposal_pow_wildcard_on_0 = true;
    new_proposal_pow_wildcard_on_1 = true;
    new_proposal_pow_wildcard_on_2 = true;
    new_proposal_pow_wildcard_on_3 = true;
    new_proposal_pow_wildcard_on_4 = true;
    inst_new_proposal_perm_wildcard_on_0 = true;
    inst_new_proposal_perm_wildcard_on_1 = true;
    inst_new_proposal_perm_wildcard_on_2 = true;
    inst_new_proposal_perm_wildcard_on_3 = true;
    inst_new_proposal_perm_wildcard_on_4 = true;
    nosupport_perm_map_on_0[b] = true;
    nosupport_perm_wildcard_on_1 = true;
    nosupport_perm_wildcard_on_2 = true;
    nosupport_pow_map_on_0[b] = true;
    nosupport_pow_wildcard_on_1 = true;
    nosupport_pow_wildcard_on_2 = true;
    inst_nosupport_perm_map_on_0[b] = true;
    inst_nosupport_perm_wildcard_on_1 = true;
    inst_nosupport_perm_wildcard_on_2 = true;
    support_perm_map_on_0[b] = true;
    support_perm_wildcard_on_1 = true;
    support_perm_wildcard_on_2 = true;
    support_pow_map_on_0[b] = true;
    support_pow_wildcard_on_1 = true;
    support_pow_wildcard_on_2 = true;
    inst_support_perm_map_on_0[b] = true;
    inst_support_perm_wildcard_on_1 = true;
    inst_support_perm_wildcard_on_2 = true;
    is_member_0[b] = true;
  }
  function inst_approved(string a) private {
    require((inst_approved_perm_wildcard_on_0 || inst_approved_perm_map_on_0[a]));
    proposal_approved_0[a] = true;
  }
  function inst_create_contract(address a) private {
    require((inst_create_contract_perm_wildcard_on_0 || inst_create_contract_perm_map_on_0[a]));
    new_proposal_perm_wildcard_on_0 = true;
    new_proposal_perm_wildcard_on_1 = true;
    new_proposal_perm_wildcard_on_2 = true;
    new_proposal_perm_wildcard_on_3 = true;
    new_proposal_perm_wildcard_on_4 = true;
    new_proposal_pow_wildcard_on_0 = true;
    new_proposal_pow_wildcard_on_1 = true;
    new_proposal_pow_wildcard_on_2 = true;
    new_proposal_pow_wildcard_on_3 = true;
    new_proposal_pow_wildcard_on_4 = true;
    inst_new_proposal_perm_wildcard_on_0 = true;
    inst_new_proposal_perm_wildcard_on_1 = true;
    inst_new_proposal_perm_wildcard_on_2 = true;
    inst_new_proposal_perm_wildcard_on_3 = true;
    inst_new_proposal_perm_wildcard_on_4 = true;
    nosupport_perm_map_on_0[a] = true;
    nosupport_perm_wildcard_on_1 = true;
    nosupport_perm_wildcard_on_2 = true;
    nosupport_pow_map_on_0[a] = true;
    nosupport_pow_wildcard_on_1 = true;
    nosupport_pow_wildcard_on_2 = true;
    inst_nosupport_perm_map_on_0[a] = true;
    inst_nosupport_perm_wildcard_on_1 = true;
    inst_nosupport_perm_wildcard_on_2 = true;
    support_perm_map_on_0[a] = true;
    support_perm_wildcard_on_1 = true;
    support_perm_wildcard_on_2 = true;
    support_pow_map_on_0[a] = true;
    support_pow_wildcard_on_1 = true;
    support_pow_wildcard_on_2 = true;
    inst_support_perm_map_on_0[a] = true;
    inst_support_perm_wildcard_on_1 = true;
    inst_support_perm_wildcard_on_2 = true;
    add_member_perm_map_on_0[a] = true;
    add_member_perm_wildcard_on_1 = true;
    add_member_pow_map_on_0[a] = true;
    add_member_pow_wildcard_on_1 = true;
    inst_add_member_perm_map_on_0[a] = true;
    inst_add_member_perm_wildcard_on_1 = true;
    is_member_0[a] = true;
  }
  function inst_deadline(string a) private {
    require((inst_deadline_perm_wildcard_on_0 || inst_deadline_perm_map_on_0[a]));
    approved_perm_map_on_0[a] = true;
    approved_pow_map_on_0[a] = true;
    inst_approved_perm_map_on_0[a] = true;
    proposal_active_0[a] = false;
  }
  function inst_new_proposal(string a, address b, address c, string d, string e) private {
    require((inst_new_proposal_perm_wildcard_on_0 || inst_new_proposal_perm_map_on_0[a]) && (inst_new_proposal_perm_wildcard_on_1 || inst_new_proposal_perm_map_on_1[b]) && (inst_new_proposal_perm_wildcard_on_2 || inst_new_proposal_perm_map_on_2[c]) && (inst_new_proposal_perm_wildcard_on_3 || inst_new_proposal_perm_map_on_3[d]) && (inst_new_proposal_perm_wildcard_on_4 || inst_new_proposal_perm_map_on_4[e]));
    deadline_perm_map_on_0[a] = true;
    deadline_pow_map_on_0[a] = true;
    inst_deadline_perm_map_on_0[a] = true;
    proposal_justification_1[a] = true;
    proposal_justification_1[e] = true;
    proposal_beneficiary_1[a] = true;
    proposal_beneficiary_1[c] = true;
    proposal_owner_1[a] = true;
    proposal_owner_1[b] = true;
    proposal_amount_1[a] = true;
    proposal_amount_1[d] = true;
    proposal_active_0[a] = true;
  }
  function inst_nosupport(address a, string b, string c) private {
    require((inst_nosupport_perm_wildcard_on_0 || inst_nosupport_perm_map_on_0[a]) && (inst_nosupport_perm_wildcard_on_1 || inst_nosupport_perm_map_on_1[b]) && (inst_nosupport_perm_wildcard_on_2 || inst_nosupport_perm_map_on_2[c]));
    against_1[a] = true;
    against_1[b] = true;
    proposal_active_0[b] = true;
  }
  function inst_support(address a, string b, string c) private {
    require((inst_support_perm_wildcard_on_0 || inst_support_perm_map_on_0[a]) && (inst_support_perm_wildcard_on_1 || inst_support_perm_map_on_1[b]) && (inst_support_perm_wildcard_on_2 || inst_support_perm_map_on_2[c]));
    supports_1[a] = true;
    supports_1[b] = true;
    proposal_active_0[b] = true;
  }
  function add_member(address b) public {
    address a = msg.sender;
    require(((add_member_perm_wildcard_on_0 || add_member_perm_map_on_0[a]) && (add_member_pow_wildcard_on_0 || add_member_pow_map_on_0[a])) && ((add_member_perm_wildcard_on_1 || add_member_perm_map_on_1[b]) && (add_member_pow_wildcard_on_1 || add_member_pow_map_on_1[b])));
    inst_add_member(a,b);
  }
  function approved() public {
    string a = "";
    require(((approved_perm_wildcard_on_0 || approved_perm_map_on_0[a]) && (approved_pow_wildcard_on_0 || approved_pow_map_on_0[a])));
    inst_approved(a);
  }
  function create_contract() public {
    address a = msg.sender;
    require(((create_contract_perm_wildcard_on_0 || create_contract_perm_map_on_0[a]) && (create_contract_pow_wildcard_on_0 || create_contract_pow_map_on_0[a])));
    inst_create_contract(a);
  }
  function deadline() public {
    string a = "";
    require(((deadline_perm_wildcard_on_0 || deadline_perm_map_on_0[a]) && (deadline_pow_wildcard_on_0 || deadline_pow_map_on_0[a])));
    inst_deadline(a);
  }
  function new_proposal(address b, address c, string d, string e) public {
    string a = "";
    require(((new_proposal_perm_wildcard_on_0 || new_proposal_perm_map_on_0[a]) && (new_proposal_pow_wildcard_on_0 || new_proposal_pow_map_on_0[a])) && ((new_proposal_perm_wildcard_on_1 || new_proposal_perm_map_on_1[b]) && (new_proposal_pow_wildcard_on_1 || new_proposal_pow_map_on_1[b])) && ((new_proposal_perm_wildcard_on_2 || new_proposal_perm_map_on_2[c]) && (new_proposal_pow_wildcard_on_2 || new_proposal_pow_map_on_2[c])) && ((new_proposal_perm_wildcard_on_3 || new_proposal_perm_map_on_3[d]) && (new_proposal_pow_wildcard_on_3 || new_proposal_pow_map_on_3[d])) && ((new_proposal_perm_wildcard_on_4 || new_proposal_perm_map_on_4[e]) && (new_proposal_pow_wildcard_on_4 || new_proposal_pow_map_on_4[e])));
    inst_new_proposal(a,b,c,d,e);
  }
  function nosupport(string b, string c) public {
    address a = msg.sender;
    require(((nosupport_perm_wildcard_on_0 || nosupport_perm_map_on_0[a]) && (nosupport_pow_wildcard_on_0 || nosupport_pow_map_on_0[a])) && ((nosupport_perm_wildcard_on_1 || nosupport_perm_map_on_1[b]) && (nosupport_pow_wildcard_on_1 || nosupport_pow_map_on_1[b])) && ((nosupport_perm_wildcard_on_2 || nosupport_perm_map_on_2[c]) && (nosupport_pow_wildcard_on_2 || nosupport_pow_map_on_2[c])));
    inst_nosupport(a,b,c);
  }
  function support(string b, string c) public {
    address a = msg.sender;
    require(((support_perm_wildcard_on_0 || support_perm_map_on_0[a]) && (support_pow_wildcard_on_0 || support_pow_map_on_0[a])) && ((support_perm_wildcard_on_1 || support_perm_map_on_1[b]) && (support_pow_wildcard_on_1 || support_pow_map_on_1[b])) && ((support_perm_wildcard_on_2 || support_perm_map_on_2[c]) && (support_pow_wildcard_on_2 || support_pow_map_on_2[c])));
    inst_support(a,b,c);
  }
}
